#!/usr/bin/env bash
# 将系统默认 JDK 设为 21（java / javac / JAVA_HOME）
# 现行 Jenkins LTS 最低要求 Java 21
# 用法：sudo bash set-default-jdk21.sh
set -euo pipefail

if [[ "$(id -u)" -ne 0 ]]; then
  echo "请使用 root 或 sudo 运行" >&2
  exit 1
fi

resolve_jdk21_home() {
  local candidates=(
    /usr/lib/jvm/java-21-openjdk-amd64
    /usr/lib/jvm/java-21-openjdk-arm64
    /usr/lib/jvm/temurin-21-jdk-amd64
    /usr/lib/jvm/temurin-21-jdk-arm64
  )
  local d
  for d in "${candidates[@]}"; do
    if [[ -x "${d}/bin/java" ]]; then
      echo "${d}"
      return 0
    fi
  done
  if command -v update-java-alternatives >/dev/null 2>&1; then
    local alt
    alt="$(update-java-alternatives -l 2>/dev/null | awk '/1\.21\.|java-21|jdk-21/ {print $3; exit}')"
    if [[ -n "${alt}" && -x "${alt}/bin/java" ]]; then
      echo "${alt}"
      return 0
    fi
  fi
  return 1
}

JDK21_HOME="$(resolve_jdk21_home || true)"
if [[ -z "${JDK21_HOME}" ]]; then
  echo "未找到 JDK 21，请先安装: sudo apt-get install -y openjdk-21-jdk" >&2
  exit 1
fi

echo "使用 JDK 21: ${JDK21_HOME}"

if command -v update-java-alternatives >/dev/null 2>&1; then
  ALT_NAME="$(update-java-alternatives -l 2>/dev/null | awk -v home="${JDK21_HOME}" '$3 == home {print $1; exit}')"
  if [[ -n "${ALT_NAME}" ]]; then
    update-java-alternatives --set "${ALT_NAME}"
  else
    update-alternatives --set java  "${JDK21_HOME}/bin/java"  2>/dev/null || \
      update-alternatives --install /usr/bin/java  java  "${JDK21_HOME}/bin/java"  2111
    update-alternatives --set javac "${JDK21_HOME}/bin/javac" 2>/dev/null || \
      update-alternatives --install /usr/bin/javac javac "${JDK21_HOME}/bin/javac" 2111
  fi
else
  update-alternatives --install /usr/bin/java  java  "${JDK21_HOME}/bin/java"  2111
  update-alternatives --install /usr/bin/javac javac "${JDK21_HOME}/bin/javac" 2111
  update-alternatives --set java  "${JDK21_HOME}/bin/java"
  update-alternatives --set javac "${JDK21_HOME}/bin/javac"
fi

cat > /etc/profile.d/jdk-default.sh <<EOF
# Generated by set-default-jdk21.sh — 系统默认 JDK 21（Jenkins LTS 要求）
export JAVA_HOME="${JDK21_HOME}"
case ":\$PATH:" in
  *":\$JAVA_HOME/bin:"*) ;;
  *) export PATH="\$JAVA_HOME/bin:\$PATH" ;;
esac
EOF
chmod 644 /etc/profile.d/jdk-default.sh

export JAVA_HOME="${JDK21_HOME}"
export PATH="${JAVA_HOME}/bin:${PATH}"

echo
echo "==== 默认 JDK 已设为 21 ===="
echo "JAVA_HOME=${JAVA_HOME}"
java -version
javac -version
echo
echo "构建 web-test 时请显式使用 JDK 8："
echo "  export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"
