[program:web-test]
command=/opt/web-test/start-app.sh
directory=/opt/web-test
user=deploy
autostart=true
autorestart=true
startsecs=5
startretries=3
stopwaitsecs=30
stopsignal=TERM
redirect_stderr=false
stdout_logfile=/opt/app-logs/web-test.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile=/opt/app-logs/web-test.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
environment=APP_PORT="8088",JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64",LANG="en_US.UTF-8",TZ="Asia/Shanghai"
